import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/NavBar";
import {Roboto} from 'next/font/google';
import NavBar from "@/components/NavBar";

const roboto = Roboto({
    weight: '700',
    subsets: ['latin'],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html suppressHydrationWarning lang="en">
        <body className={roboto.className}>
        <main className="w-full">{children}</main>
        </body>
        </html>
    );
}
