import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/NavBar";
import {Roboto} from "next/dist/compiled/@next/font/dist/google";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html suppressHydrationWarning lang="en">
        <body >
        <main className="w-full">{children}</main>
        </body>
        </html>
    );
}
